name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Before submitting, check if it's already in [FUTURE_ENHANCEMENTS.md](../FUTURE_ENHANCEMENTS.md)

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Screen/View
        - Data Management
        - Rules Engine Enhancement
        - UI/UX Improvement
        - Performance Optimization
        - Developer Experience
        - Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) should this affect?
      multiple: true
      options:
        - Desktop (all)
        - Mobile (all)
        - Desktop (Windows)
        - Desktop (macOS)
        - Desktop (Linux)
        - Mobile (Android)
        - Mobile (iOS)
        - Both Desktop and Mobile
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed feature
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Add mockups, wireframes, or examples
      placeholder: Drag and drop images here

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Critical - Blocking my usage
        - High - Would significantly improve experience
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute?
      options:
        - label: I can implement this feature
        - label: I can help test this feature
        - label: I can write documentation for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
